メモの保存先をPostgreSQLに変更
bore-ko/sinatra-practice pull request #2
Opened 2023-06-18 11:23 UTC by bore-ko

2023-06-24 15:49 UTC, u1tnk requested changes

2023-06-24 15:49 UTC, u1tnk commented on memo.rb
> +  conn = PG.connect(dbname: 'memos')
まず、接続処理は何度も呼ぶものなので共通化しましょう。

2023-06-27 12:28 UTC, bore-ko commented on memo.rb
> +  conn = PG.connect(dbname: 'memos')
ありがとうございます！共通化するようにしました。

2023-06-27 14:20 UTC, u1tnk approved these changes
問題ありません！ お疲れ様でした。

2023-07-01 01:39 UTC, merged